services:
    kismet:
        privileged: true
        network_mode: host
        pid: host
        image: porkiedev/kismet
        command: ["/usr/local/bin/kismet", "--no-ncurses-wrapper", "--config-file", "/data-kismet/config/kismet.conf", "--log-prefix", "/data-kismet/output", "--homedir", "/data-kismet/home", "--confdir", "/data-kismet/config", "--override", "wardrive"]
        restart: unless-stopped
        volumes:
          - ./data-kismet:/data-kismet
